
services:
  mapproxy:
    build:
      context: ./mapproxy
      dockerfile: dockerfile
    container_name: wonderland-mapproxy
    ports:
      - "8081:80"
    volumes:
      - ./mapproxy/mapproxy.yml:/mapproxy/config/mapproxy.yaml:ro
      - ./dev_data/mapproxy/cache:/mapproxy/config/cache_data
      - ./dev_data/mapproxy/maps:/mapproxy/maps
    networks:
      - magenim-net
    restart: unless-stopped

  postgres:
    image: postgis/postgis:16-3.4
    container_name: magenim-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: wonderland
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - magenim-net
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: wonderland-mediamtx
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "9997:9997"
      - "8189:8189/udp"
      - "8199:8199"
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml:ro
    networks:
      - magenim-net
    restart: unless-stopped

networks:
  magenim-net:
    driver: bridge

volumes:
  postgres_data:
