
services:
  mapproxy:
      image: kartoza/mapproxy:latest
      container_name: map-proxy-server
      volumes:
        - ./mapproxy/mapproxy.yml:/mapproxy/mapproxy.yml:ro
        - ./mapproxy/maps:/mapproxy/maps
      ports:
        - "8080:8080"
      networks:
        - magenim-net
      restart: unless-stopped
      command: >
        mapproxy-util serve-develop /mapproxy/mapproxy.yml -b 0.0.0.0:8080
      
  postgres:
    image: postgis/postgis:16-3.4
    container_name: magenim-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: wonderland
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - magenim-net
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: wonderland-mediamtx
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "9997:9997"
      - "8189:8189/udp"
      - "8199:8199"
      - "9996:9996"
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml:ro
      - ./recordings:/recordings
    networks:
      - magenim-net
    restart: unless-stopped

networks:
  magenim-net:
    driver: bridge

volumes:
  postgres_data:
